### ISSUE TITLE
digitalWrite.py giving error

### ISSUE THREAD

**Issue by renesteeman** [ZeroPiProject/PythonForZeroPi#1]
I installed everything as told, but when I run digitalWrite.py I get a line 5: syntax error and a line 5: '     bot = zeropi()'

Further I'm still not able to use the GPIO pins as I want, I just need to control 4 LED's with them, how can I make a file that will turn the A0 line on or off when called upon?

**Comment by renesteeman** [comment]
And why does the digitalWrite.py call for pin 13? Shouldn't it be A0, A1, A2 or A3 and so on?

**Comment by renesteeman** [comment]
The cmd also stoped working after I typed sudo python digitalWrite.py why does this happen? And could you please share you're webcontrol projects.

**Comment by xeecos** [comment]
A0 ~ A5 added, and pins MO MI SDA SCL SCK.
